-- ==========================================
-- 📊 Esquema de Base de Datos - FinanzasApp
-- ==========================================

-- 1. Tabla: categorias_presupuesto
-- Almacena los límites de gasto mensual por categoría para cada usuario.
CREATE TABLE IF NOT EXISTS public.categorias_presupuesto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    nombre VARCHAR(100) NOT NULL,
    limite_mensual DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    creado_en TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    CONSTRAINT limite_positivo CHECK (limite_mensual >= 0)
);

-- Indexar usuario_id para optimizar las consultas y joins
CREATE INDEX IF NOT EXISTS idx_categorias_usuario ON public.categorias_presupuesto(usuario_id);

-- 2. Tabla: transacciones
-- Registra los ingresos y gastos hormiga del usuario.
CREATE TABLE IF NOT EXISTS public.transacciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    categoria_id BIGINT REFERENCES public.categorias_presupuesto(id) ON DELETE SET NULL,
    monto DECIMAL(12,2) NOT NULL,
    descripcion VARCHAR(255) NOT NULL,
    metodo_pago VARCHAR(50) NOT NULL,
    tipo VARCHAR(20) NOT NULL,
    fecha_transaccion TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    creado_en TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    -- Restricciones de validación
    CONSTRAINT monto_positivo CHECK (monto > 0),
    CONSTRAINT check_metodo_pago CHECK (metodo_pago IN ('Nequi', 'Tarjeta Crédito', 'Tarjeta Débito', 'Efectivo')),
    CONSTRAINT check_tipo CHECK (tipo IN ('Ingreso', 'Gasto'))
);

-- Indexar usuario_id y fecha para agilizar el Dashboard e histórico
CREATE INDEX IF NOT EXISTS idx_transacciones_usuario ON public.transacciones(usuario_id);
CREATE INDEX IF NOT EXISTS idx_transacciones_fecha ON public.transacciones(fecha_transaccion DESC);

-- ==========================================
-- 🔒 Row Level Security (RLS)
-- ==========================================

-- Habilitar RLS en ambas tablas
ALTER TABLE public.categorias_presupuesto ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transacciones ENABLE ROW LEVEL SECURITY;

-- Políticas para: categorias_presupuesto
CREATE POLICY "Permitir lectura de categorías propias" 
    ON public.categorias_presupuesto FOR SELECT 
    USING (auth.uid() = usuario_id);

CREATE POLICY "Permitir inserción de categorías propias" 
    ON public.categorias_presupuesto FOR INSERT 
    WITH CHECK (auth.uid() = usuario_id);

CREATE POLICY "Permitir actualización de categorías propias" 
    ON public.categorias_presupuesto FOR UPDATE 
    USING (auth.uid() = usuario_id) 
    WITH CHECK (auth.uid() = usuario_id);

CREATE POLICY "Permitir eliminación de categorías propias" 
    ON public.categorias_presupuesto FOR DELETE 
    USING (auth.uid() = usuario_id);

-- Políticas para: transacciones
CREATE POLICY "Permitir lectura de transacciones propias" 
    ON public.transacciones FOR SELECT 
    USING (auth.uid() = usuario_id);

CREATE POLICY "Permitir inserción de transacciones propias" 
    ON public.transacciones FOR INSERT 
    WITH CHECK (auth.uid() = usuario_id);

CREATE POLICY "Permitir actualización de transacciones propias" 
    ON public.transacciones FOR UPDATE 
    USING (auth.uid() = usuario_id) 
    WITH CHECK (auth.uid() = usuario_id);

CREATE POLICY "Permitir eliminación de transacciones propias" 
    ON public.transacciones FOR DELETE 
    USING (auth.uid() = usuario_id);

-- ==========================================
-- ⚡ Trigger: Inicializar Categorías por Defecto
-- ==========================================
-- Cuando un usuario se registra en Supabase Auth, se crean automáticamente 
-- las categorías básicas de presupuesto para facilitarle el inicio.

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.categorias_presupuesto (usuario_id, nombre, limite_mensual)
    VALUES
        (new.id, 'Comida', 500000.00),
        (new.id, 'Transporte', 150000.00),
        (new.id, 'Entretenimiento', 200000.00),
        (new.id, 'Servicios', 300000.00),
        (new.id, 'Otros', 100000.00);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger disparado tras la inserción en auth.users
CREATE OR REPLACE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
